FROM node:14

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

ARG NODE_ENV=${NODE_ENV}
ENV NODE_ENV=${NODE_ENV}
ARG NEXT_PUBLIC_MAILJS_API=${NEXT_PUBLIC_MAILJS_API}
ENV NEXT_PUBLIC_MAILJS_API=${NEXT_PUBLIC_MAILJS_API}
ARG NEXT_PUBLIC_ZIGAH_APP_URL=${NEXT_PUBLIC_ZIGAH_APP_URL}
ENV NEXT_PUBLIC_ZIGAH_APP_URL=${NEXT_PUBLIC_ZIGAH_APP_URL}

RUN yarn build

EXPOSE 9009

CMD ["yarn", "start"]
